title: That place you dare not look
author: Tony Anter
email: anter.tony@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  When you look in that place you dare not look, you will see me there staring back at you. I am the qwisatz haderack

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
